version: '3.9'

services:
  db:
    image: postgres:15
    container_name: ss_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-db
    ports:
      - "5432:5432"
  web:
    image: ss_web:latest
    container_name: ss_django
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env-app
      - .env-db
    ports:
      - "8000:8000"

volumes:
  static_volume:
  media_volume:
  postgres_data: