# Generated by Django 4.2.5 on 2023-10-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.FileField(default='document', upload_to='uploads/documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
    ]
