# Generated by Django 4.2.5 on 2023-10-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='isRead',
            new_name='is_read',
        ),
    ]
