# Generated by Django 4.2.5 on 2023-10-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Ready', 'Ready'), ('Received', 'Received')], default='Processing'),
        ),
    ]
